#!/usr/bin/env python

import getpass
import os
import sys
import hashlib
from os.path import isdir
from argparse import ArgumentParser
from sos.ls_tui import LSLayout
from ls_syscall import ls_reload, ls_logout
from sos.user import login, logout


__version__ = "0.1.2"
RED = "\033[0;31m"
GREEN = "\033[0;32m"
NC = '\033[0m'  # No Color


parser = ArgumentParser(description="SOS module manager")

parser.add_argument(
    "mode",
    metavar="mode",
    type=str,
    default=["manager"],
    help="login | logout | reload | manager | encrypt | unlock | lock | passwd"
)

parser.add_argument(
    "--options",
    "-o",
    metavar="options",
    type=str,
    default="",
    required=False,
    help="options depned on mode"
)


args = parser.parse_args()


def main():
    if args.mode == 'login':
        passwd = getpass.getpass()
        ret = login(hashlib.sha1(passwd).digest())

        if ret != 0:
            sys.stderr.write(RED + "Operation not permitted\n" + NC)
            sys.exit(-1)
    elif args.mode == 'logout':
        logout()
    elif args.mode == 'reload':
        ret = ls_reload()

        if ret != 0:
            sys.stderr.write(RED + "Operation not permitted\n" + NC)
            sys.exit(-1)
    elif args.mode == 'manager':
        if not os.access("/etc/data.sos", os.W_OK):
	    sys.stderr.write(RED + "Operation not permitted\n" + NC)
            sys.exit(-1)    	
        passwd = getpass.getpass()
        ret = login(hashlib.sha1(passwd).digest())

        if ret != 0:
            sys.stderr.write(RED + "Operation not permitted\n" + NC)
            sys.exit(-1)
        LSLayout()
        ls_reload()
        ls_logout()
    elif args.mode == 'encrypt' or args.mode == 'unlock':
        if not len(args.options) == 0:
            target = args.options
            if isdir(target):
		# keyctl
                passwd = getpass.getpass("Encryption password: ")
                os.system(
                    "keyctl new_session 1>/dev/null && mount -t  ecryptfs "
                    + target + " "
                    + target
                    + " -o key=passphrase:passphrase_passwd=" + passwd
                    + " -o ecryptfs_enable_filename_crypto=n"
                    + " -o ecryptfs_cipher=aes"
                    + " -o ecryptfs_key_bytes=24"
                    + " -o ecryptfs_passthrough 1>/dev/null"
                )
                print(GREEN + "Encrypted" + NC)
            else:
                sys.stderr.write(RED + "SRC_DIR is not directory\n" + NC)
                sys.exit(-1)
        else:
            sys.stderr.write(RED + "sos ecrypt [SRC_DIR]\n" + NC)
            sys.exit(-1)
    elif args.mode == 'lock':
        if not len(args.options) == 0:
            target = args.options
            if isdir(target):
                os.system("umount " + target + " 1>/dev/null")
            else:
                sys.stderr.write(RED + "SRC_DIR is not directory\n" + NC)
                sys.exit(-1)
        else:
            sys.stderr.write(RED + "sos ecrypt [SRC_DIR]\n" + NC)
            sys.exit(-1)
    elif args.mode == 'passwd':
        passwd = getpass.getpass("Old Password: ")
        ret = login(hashlib.sha1(passwd).digest())
     
        if ret != 0:
            sys.stderr.write(RED + "Operation not permitted\n" + NC)
            sys.exit(-1)

	passwd = getpass.getpass("New Password: ")
        hash_passwd = hashlib.sha1(passwd).digest()

        f = open('/etc/data.sos', 'rb')
        data = bytearray(f.read())
        f.close()

        f = open('/etc/data.sos', 'wb')
        if len(data) > 20:
            f.write(hash_passwd + data[20:])
        else:
            f.write(hash_passwd)
        f.close()

        ls_reload()
    else:
	print(RED + args.mode + " is unknown" + NC)
        parser.print_help()

if __name__ == '__main__':
    main()
